<?php
/**
 * Created by PhpStorm.
 * User: pradeep
 * Date: 2014-12-14
 * Time: 03:21 PM
 */

class PermissionsTableSeeder extends Seeder
{

    public function run()
    {
        $users = [
            [   'name' => 'Allow Login',
                'slug' => 'allow-login',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'API Access',
                'slug' => 'api-access',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Dashboard Activity Log',
                'slug' => 'allow-dashboard-activity-log',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Show Admin Section',
                'slug' => 'show-admin-section',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Bulk Active',
                'slug' => 'allow-bulk-active',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Bulk Deactive',
                'slug' => 'allow-bulk-deactive',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Bulk Delete',
                'slug' => 'allow-bulk-delete',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow To View Trash',
                'slug' => 'allow-to-view-trash',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Permanent Delete',
                'slug' => 'allow-permanent-delete',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow To Restore',
                'slug' => 'allow-to-restore',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Active/Deactive',
                'slug' => 'allow-activedeactive',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Soft Delete',
                'slug' => 'allow-soft-delete',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow Ajax Edit',
                'slug' => 'allow-ajax-edit',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow To Add User',
                'slug' => 'allow-to-add-user',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow To Edit User',
                'slug' => 'allow-to-edit-user',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Manage Group Permission',
                'slug' => 'manage-group-permission',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'View Activities',
                'slug' => 'view-activities',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow To Add Group',
                'slug' => 'allow-to-add-group',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ],
            [   'name' => 'Allow To Add Permission',
                'slug' => 'allow-to-add-permission',
                'active' => 1,
                'created_at' => Dates::now(),
                'updated_at' => Dates::now(),
            ]

        ];

        DB::table('permissions')->insert($users);

    }

}